apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server
  namespace: argocd
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
spec:
  destination:
    namespace: {{ .Values.namespace-global }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated: {}
  project: default
  source:
    path: cmp-apps
    helm:
      valueFiles:
        - values-config-server.yaml
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
