apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: global
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: global
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
  project: default
  source:
    path: cmp
    helm:
      valueFiles:
        - values-config.yaml
    repoURL: https://github.com/rioma0200/argocd-example-apps
    targetRevision: HEAD
