apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cp-web
  namespace: argocd
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "3"
spec:
  destination:
    namespace: {{ .Values.namespaceGlobal }}
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
  source:
    path: cmp-apps
    helm:
      valueFiles:
        - values-cp-web.yaml
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
