apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eureka
  namespace: argocd
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  destination:
    namespace: global-test
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated: {}
  project: default
  source:
    path: cmp-apps
    helm:
      valueFiles:
        - values-eureka.yaml
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
