apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eureka
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
  project: default
  source:
    path: eureka
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/rioma0200/argocd-example-apps
    targetRevision: HEAD
