apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eureka
  namespace: argocd
  annotations:
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "1"
spec:
  destination:
    namespace: global-test1
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
  project: default
  source:
    path: cmp
    helm:
      valueFiles:
        - values-eureka.yaml
    repoURL: https://github.com/rioma0200/argocd-example-apps
    targetRevision: HEAD
