apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: global-area
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: global-area
    server: {{ .Values.spec.destination.server }}
  syncPolicy:
    automated: {}
  project: default
  source:
    path: helm-guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
