apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace-global }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace-east }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace-north }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

