apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceGlobal }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceEast }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaceNorth }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"

