apiVersion: batch/v1
kind: Job
metadata:
  name: post-check-15s
  annotations:
    helm.sh/hook: post-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-1"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "15"]
      restartPolicy: Never
  backoffLimit: 0
